export const NEWS_FETCH_START = 'NEWS_FETCH_START';
export const NEWS_FETCH_SUCCESS = 'NEWS_FETCH_SUCCESS';
export const NEWS_FETCH_FAILURE = 'NEWS_FETCH_FAILURE';

export const SELECTED_NEWS_FETCH_START = 'SELECTED_NEWS_FETCH_START';
export const SELECTED_NEWS_FETCH_SUCCESS = 'SELECTED_NEWS_FETCH_SUCCESS';
export const SELECTED_NEWS_FETCH_FAILURE = 'SELECTED_NEWS_FETCH_FAILURE';

export const COMMENTS_FETCH_START = 'COMMENTS_FETCH_START';
export const COMMENTS_FETCH_SUCCESS = 'COMMENTS_FETCH_SUCCESS';
export const COMMENT_FETCH_SUCCESS = 'COMMENT_FETCH_SUCCESS';
export const COMMENTS_FETCH_FAILURE = 'COMMENTS_FETCH_FAILURE';

export const KIDS_FETCH_START = 'KIDS_FETCH_START';
export const KIDS_FETCH_SUCCESS = 'KIDS_FETCH_SUCCESS';
export const KIDS_FETCH_FAILURE = 'KIDS_FETCH_FAILURE';